# ADOBE CONFIDENTIAL
#
# Copyright 2010-2024 Adobe
# All Rights Reserved.
#
# NOTICE:  Adobe permits you to use, modify, and distribute this file in
# accordance with the terms of the Adobe license agreement accompanying it.
# If you have received this file from a source other than Adobe,
# then your use, modification, or distribution of it requires the prior
# written permission of Adobe.
#
# Autogenerated by ipa. Don't edit directly, edit the definitions and regenerate it when changing
#

from __future__ import annotations

import ctypes
import base64

from typing import Any, Optional

import sd
from .sdvaluevector import *
from .sdapiobject import *
from .sdbasetypes import *
from .sdapiobject import *
from .apiexception import APIException

class SDValueBool2(SDValueVector):
    def __init__(self, APIContext, handle, *args, **kwargs):
        """
        Constructor

        :rtype: SDValueBool2
        """
        super(SDValueBool2, self).__init__(APIContext, handle, *args, **kwargs)

    @staticmethod
    def sNew(value : bool2) -> SDValueBool2:
        """
        Create new SDValueBool2

        :param value: The name of the enum type
        """
        outSDValueBool2 = ctypes.c_void_p()
        _res = sd.getContext().SDValueBool2_sNew(ctypes.byref(value), ctypes.byref(outSDValueBool2))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None # type: ignore
            raise APIException(SDApiError(_res))
        constructor = sd.getContext().mTypeMap[SDAPIObject(sd.getContext(), outSDValueBool2, ownHandle=False).getClassName()]
        return constructor(sd.getContext(), outSDValueBool2.value, ownHandle=True)

    def get(self) -> bool2:
        """
        Get the base type value as bool2

        """
        outValue = bool2()
        _res = self.mAPIContext.SDValueBool2_get(self.mHandle, ctypes.byref(outValue))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None # type: ignore
            raise APIException(SDApiError(_res))
        return outValue

