# ADOBE CONFIDENTIAL
#
# Copyright 2010-2024 Adobe
# All Rights Reserved.
#
# NOTICE:  Adobe permits you to use, modify, and distribute this file in
# accordance with the terms of the Adobe license agreement accompanying it.
# If you have received this file from a source other than Adobe,
# then your use, modification, or distribution of it requires the prior
# written permission of Adobe.
#
# Autogenerated by ipa. Don't edit directly, edit the definitions and regenerate it when changing
#

from __future__ import annotations

import ctypes
import base64

from typing import Any, Optional

import sd
from .sdvaluebasetype import SDValueBaseType
from .sdapiobject import SDAPIObject
from .sdapiobject import SDApiError
from .apiexception import APIException

class SDValueDouble(SDValueBaseType):
    """
    Class representing a double precision floatting point Value
    """
    def __init__(self, APIContext, handle, *args, **kwargs):
        """
        Constructor

        :rtype: SDValueDouble
        """
        super(SDValueDouble, self).__init__(APIContext, handle, *args, **kwargs)

    @staticmethod
    def sNew(value : float) -> SDValueDouble:
        """
        Create new SDValueDouble

        :param value: The name of the enum type
        """
        outSDValueDouble = ctypes.c_void_p()
        _res = sd.getContext().SDValueDouble_sNew(value, ctypes.byref(outSDValueDouble))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None # type: ignore
            raise APIException(SDApiError(_res))
        constructor = sd.getContext().mTypeMap[SDAPIObject(sd.getContext(), outSDValueDouble, ownHandle=False).getClassName()]
        return constructor(sd.getContext(), outSDValueDouble.value, ownHandle=True)

    def get(self) -> float:
        """
        Get the base type value as double

        """
        outValue = ctypes.c_double()
        _res = self.mAPIContext.SDValueDouble_get(self.mHandle, ctypes.byref(outValue))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None # type: ignore
            raise APIException(SDApiError(_res))
        return outValue.value

